src/main/java/mb/EnumManagedBean.java
package mb;

import java.util.Arrays;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import enums.ActionType;
import enums.EditingSuggestion;
import enums.EventStatus;
import enums.Permission;

/**	Managed Bean to make specific enum objects accessable to the EL.
 * 	@author 	Annina Biermann
 */
@ManagedBean
@RequestScoped
public class EnumManagedBean {

    // ACTION TYPES

    public ActionType getTypeObjCreated() {
	return ActionType.OBJECT_CREATED;
    }

    public ActionType getTypeObjEdited() {
	return ActionType.OBJECT_EDITED;
    }

    public ActionType getTypeObjDeleted() {
	return ActionType.OBJECT_DELETED;
    }

    public ActionType getTypeEventRejected() {
	return ActionType.EVENT_REJECTED;
    }

    public ActionType getTypeEventRevived() {
	return ActionType.EVENT_REVIVED;
    }

    public ActionType getTypeEventApproved() {
	return ActionType.EVENT_APPROVED;
    }

    public ActionType getTypeEventCancelled() {
	return ActionType.EVENT_CANCELLED;
    }

    public ActionType getTypeEventArchived() {
	return ActionType.EVENT_ARCHIVED;
    }

    public ActionType getTypeEventContinued() {
	return ActionType.EVENT_CONTINUED;
    }

    // EDITING SUGGESTIONS

    public EditingSuggestion getNoEditingSuggestion() {
	return EditingSuggestion.NO_EDITING;
    }

    public EditingSuggestion getGeneralEditingSuggestion() {
	return EditingSuggestion.GENERAL_EDITING;
    }

    public EditingSuggestion getContinuingEditingSuggestion() {
	return EditingSuggestion.CONTINUING_EDITING;
    }

    // EVENT STATUS

    public EventStatus getUnderExamination() {
	return EventStatus.UNDER_EXAMINATION;
    }

    public EventStatus getRejected() {
	return EventStatus.REJECTED;
    }

    public EventStatus getApproved() {
	return EventStatus.APPROVED;
    }

    public EventStatus getCancelled() {
	return EventStatus.CANCELLED;
    }

    public List<EventStatus> getAllEventStatus() {
	return Arrays.asList(EventStatus.values());
    }

    // PERMISSIONS

    public List<Permission> getAllPermissions() {
	return Arrays.asList(Permission.values());
    }
}

src/main/webapp/authentifiziert/benutzer/bearbeiten.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<f:metadata>
	<f:viewParam name="userId" value="#{editUserManagedBean.userId}" />
	<f:viewAction action="#{editUserManagedBean.onLoad}" />
</f:metadata>

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">
		<h:link class="backButton" outcome="/authentifiziert/benutzer.xhtml">
			<span class="glyphicon glyphicon-arrow-left" /> Zurück zur Benutzerverwaltung
		</h:link>

		<div class="formContainer">
			<h3>Benutzer #{editUserManagedBean.editedUser.username}
				bearbeiten</h3>
			<h:form id="editUserForm">

				<h:messages id="editedUserMessages" class="errorMessages"
					showDetail="true" showSummary="false" />

				<div class="form-group">
					<h:outputLabel for="username" value="Benutzername:" />
					<p:inputText class="inputText" id="username"
						value="#{editUserManagedBean.editedUser.username}" required="true"
						requiredMessage="Der Benutzername darf nicht leer sein!" />
				</div>

				<div class="form-group">
					<h:outputLabel for="editUserPermissionList" value="Berechtigungen:" />
					<p:selectManyCheckbox id="editUserPermissionList"
						class="inputManyCheckboxes"
						value="#{editUserManagedBean.editedUser.permissions}"
						layout="pageDirection" converter="permissionConverter"
						collectionType="java.util.ArrayList">
						<f:selectItems value="#{enumManagedBean.allPermissions}"
							var="permission" itemLabel="#{permission.toString()}"
							itemValue="#{permission}" />
					</p:selectManyCheckbox>
				</div>

				<h:commandLink class="btn btn-primary pull-right create-btn"
					action="#{editUserManagedBean.editUser}">
					Benutzer speichern
				</h:commandLink>

			</h:form>
		</div>
	</div>

	<sefb:footer />
	<sefb:js-footer />

</h:body>
</html>

src/main/webapp/authentifiziert/benutzer/neu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">
		<h:link class="backButton" outcome="/authentifiziert/benutzer.xhtml">
			<span class="glyphicon glyphicon-arrow-left" /> Zurück zur Benutzerverwaltung
		</h:link>

		<div class="formContainer">
			<h3>Neuen Benutzer anlegen</h3>
			<h:form id="createUserForm">
			
				<h:messages id="newUserMessages" class="errorMessages"
						showDetail="true" showSummary="false" />

				<div class="form-group">
					<h:outputLabel for="username" value="Benutzername:" />
					<p:inputText class="inputText" id="username"
						value="#{createUserManagedBean.newUser.username}" required="true"
							requiredMessage="Der Benutzername darf nicht leer sein!"
							a:placeholder="Benutzername des neuen Benutzers"/>
				</div>

				<div class="form-group">
					<h:outputLabel for="password1" value="Passwort:" />
					<p:password class="inputText" id="password1"
						value="#{createUserManagedBean.password}" required="true"
							requiredMessage="Die Passwörter darf nicht leer sein!"
							a:placeholder="Passwort des neuen Benutzers"/>
				</div>

				<div class="form-group">
					<h:outputLabel for="password2" value="Passwort Wiederholung:" />
					<p:password class="inputText" id="password2"
						value="#{createUserManagedBean.passwordRepetition}"  required="true"
							requiredMessage="Die Passwörter darf nicht leer sein!"
							a:placeholder="Passwort des neuen Benutzers wiederholen"/>
				</div>

				<div class="form-group">
					<h:outputLabel for="createUserPermissionList"
						value="Berechtigungen:" />
					<p:selectManyCheckbox id="createUserPermissionList"
						class="inputManyCheckboxes" value="#{createUserManagedBean.newUser.permissions}"
						layout="pageDirection" converter="permissionConverter">
						<f:selectItems value="#{enumManagedBean.allPermissions}"
							var="permission" itemLabel="#{permission.toString()}"
							itemValue="#{permission}" />
					</p:selectManyCheckbox>
				</div>

				<h:commandLink class="btn btn-primary pull-right create-btn"
					action="#{createUserManagedBean.createUser}">
					Benutzer anlegen
				</h:commandLink>

			</h:form>
		</div>
	</div>
	
	<sefb:footer />
	<sefb:js-footer />
	
</h:body>
</html>