src/main/java/mb/EnumManagedBean.java
package mb;

import java.util.Arrays;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import enums.ActionType;
import enums.EditingSuggestion;
import enums.EventStatus;
import enums.Permission;

/**	Managed Bean to make specific enum objects accessable to the EL.
 * 	@author 	Annina Biermann
 */
@ManagedBean
@RequestScoped
public class EnumManagedBean {

    // ACTION TYPES

    public ActionType getTypeObjCreated() {
	return ActionType.OBJECT_CREATED;
    }

    public ActionType getTypeObjEdited() {
	return ActionType.OBJECT_EDITED;
    }

    public ActionType getTypeObjDeleted() {
	return ActionType.OBJECT_DELETED;
    }

    public ActionType getTypeEventRejected() {
	return ActionType.EVENT_REJECTED;
    }

    public ActionType getTypeEventRevived() {
	return ActionType.EVENT_REVIVED;
    }

    public ActionType getTypeEventApproved() {
	return ActionType.EVENT_APPROVED;
    }

    public ActionType getTypeEventCancelled() {
	return ActionType.EVENT_CANCELLED;
    }

    public ActionType getTypeEventArchived() {
	return ActionType.EVENT_ARCHIVED;
    }

    public ActionType getTypeEventContinued() {
	return ActionType.EVENT_CONTINUED;
    }

    // EDITING SUGGESTIONS

    public EditingSuggestion getNoEditingSuggestion() {
	return EditingSuggestion.NO_EDITING;
    }

    public EditingSuggestion getGeneralEditingSuggestion() {
	return EditingSuggestion.GENERAL_EDITING;
    }

    public EditingSuggestion getContinuingEditingSuggestion() {
	return EditingSuggestion.CONTINUING_EDITING;
    }

    // EVENT STATUS

    public EventStatus getUnderExamination() {
	return EventStatus.UNDER_EXAMINATION;
    }

    public EventStatus getRejected() {
	return EventStatus.REJECTED;
    }

    public EventStatus getApproved() {
	return EventStatus.APPROVED;
    }

    public EventStatus getCancelled() {
	return EventStatus.CANCELLED;
    }

    public List<EventStatus> getAllEventStatus() {
	return Arrays.asList(EventStatus.values());
    }

    // PERMISSIONS

    public List<Permission> getAllPermissions() {
	return Arrays.asList(Permission.values());
    }
}

src/main/java/mb/EventManagedBean.java
package mb;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import bo.Event;
import enums.EventStatus;
import helper.FacesHelper;
import services.ActionService;
import services.EventService;
import services.ServiceFactory;

/**	A Managed Bean responsible for event related user interactions.
 * 	@author	Annina Biermann
 */
@ManagedBean(eager = true)
@ViewScoped
public class EventManagedBean implements Serializable {
    private static final long serialVersionUID = -1401794265492568212L;

    /**	An action service for logging and finding actions.	*/
    private transient ActionService actionService = ServiceFactory.createActionService();
    /**	An event service for event related interactions.	*/
    private transient EventService eventService = ServiceFactory.createEventService();

    /**	The selected event filter on the event overview.	*/
    private EventStatus selectedEventStatus = EventStatus.UNDER_EXAMINATION;

    /**	Redirects to the testprocess view and passes the event ID to the view.
     * 	@return	The redirect URL.
     */
    public String openInTestProcessWizard() {
	Event selectedEvent = FacesHelper.getSelectedObject(Event.class);
	return "veranstaltungen/pruefprozessassistent?faces-redirect=true&eventId=" + selectedEvent.getId();
    }

    /**	Redirects to the event editing view and passes the event ID to the view.
     * 	@return	The redirect URL.
     */
    public String editEvent() {
	Event selectedEvent = FacesHelper.getSelectedObject(Event.class);
	return "veranstaltungen/bearbeiten?faces-redirect=true&eventId=" + selectedEvent.getId();
    }

    /**	Sets the status of the selected event to archived.
     * 	@return	The redirect URL to the same page.
     */
    public String archiveEvent() {
	Event selectedEvent = FacesHelper.getSelectedObject(Event.class);
	eventService.archiveEvent(selectedEvent);
	actionService.logEventArchived(selectedEvent);
	return null;
    }

    /**	Sets the status of the selected event to under examination.
     * 	@return	The redirect URL to the same page.
     */
    public String reviveEvent() {
	Event selectedEvent = FacesHelper.getSelectedObject(Event.class);
	eventService.reviveEvent(selectedEvent);
	actionService.logEventRevived(selectedEvent);
	return null;
    }

    /**	Returns the events depending on the choosen status from the filter dropdown.
     * 	@return	The events depending on the choosen status.
     */
    public List<Event> getFilteredEvents() {
	return eventService.findEventsWithStatus(selectedEventStatus);
    }

    // GETTER AND SETTER

    public EventStatus getSelectedEventStatus() {
	return selectedEventStatus;
    }

    public void setSelectedEventStatus(EventStatus selectedEventStatus) {
	this.selectedEventStatus = selectedEventStatus;
    }
}

src/main/java/mb/LoginManagedBean.java
package mb;

import java.io.Serializable;
import java.util.Optional;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import enums.Permission;
import helper.FacesHelper;
import provider.OutcomeStatusProvider;
import services.ServiceFactory;
import services.UserService;

/**	Managed Bean, that is responsible for regulating the login and logout of a user.
 * 	It is session scoped, since the current user is needed as long as the session exists.
 * 	@author	Annina Biermann
 */
@ManagedBean(eager = true)
@SessionScoped
public class LoginManagedBean implements Serializable {
    private static final long serialVersionUID = -1381101568311500915L;

    /**	The ID of the user, that is currently logged in.	*/
    private Integer currentUserId;
    /**	A boolean flag, if a user is logged in in the current session.	*/
    private boolean loggedIn = false;

    /**	Credentials for attempts to login.	*/
    private String username;
    private String password;

    /**	Processes an attempt to login. If 
     * 		- the given user is not existing
     * 		- the given password is invalid
     * 	an error message is created and the user remains on the login-page.
     * 	Else the user is successfully authenticated.
     * 	@return	The outcome of the login validation.
     */
    public String login() {
	UserService userService = ServiceFactory.createUserService();
	Optional<String> validateMessage = userService.validateCredentials(username, password);
	if (!validateMessage.isPresent()) {
	    setCurrentUserId(userService.findUserByUsername(username).get().getId());
	    loggedIn = true;
	    return OutcomeStatusProvider.SUCCESS;
	}
	FacesHelper.createErrorMessage(validateMessage.get(), "loginFormMessages");
	return "";
    }

    /**	Deletes the current user from the session and redirects to the login-page.
     * 	@return	The outcome of the logout.
     */
    public String logout() {
	setCurrentUserId(null);
	loggedIn = false;
	FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	return OutcomeStatusProvider.SUCCESS;
    }

    public boolean getHasUserWritingPermission() {
	return ServiceFactory.createUserService().hasUserPermission(currentUserId, Permission.WRITE);
    }

    public boolean getHasUserAdminPermission() {
	return ServiceFactory.createUserService().hasUserPermission(currentUserId, Permission.ADMINISTRATE);
    }

    // GETTER AND SETTER

    public String getUsername() {
	return username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    public String getPassword() {
	return password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    public Integer getCurrentUserId() {
	return currentUserId;
    }

    public void setCurrentUserId(Integer currentUserId) {
	this.currentUserId = currentUserId;
    }

    public boolean isLoggedIn() {
	return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
	this.loggedIn = loggedIn;
    }
}

src/main/java/mb/UserManagedBean.java
package mb;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import bo.User;
import enums.Permission;
import helper.FacesHelper;
import services.ActionService;
import services.FinderService;
import services.ServiceFactory;
import services.UserService;

/**	A Managed Bean responsible for user related user interactions.
 * 	@author	Annina Biermann
 */
@ManagedBean
@RequestScoped
public class UserManagedBean {

    /**	An action service for logging and finding actions.	*/
    private transient ActionService actionService = ServiceFactory.createActionService();
    /**	An user service for user related interactions.	*/
    private transient UserService userService = ServiceFactory.createUserService();

    /**	Redirects to the user editing view and passes the user ID to the view.
     * 	@return	The redirect URL.
     */
    public String editUser() {
	User selectedUser = FacesHelper.getSelectedObject(User.class);
	return "benutzer/bearbeiten?faces-redirect=true&userId=" + selectedUser.getId();
    }

    /**	Deletes the selected user off the persistence layer.
     * 	@return	The reference to the same page.
     */
    public String deleteUser() {
	User selectedUser = FacesHelper.getSelectedObject(User.class);
	ServiceFactory.createUserService().deleteUser(selectedUser);
	actionService.logUserDeletion(selectedUser);
	return "";
    }

    /**	Returns all users, except the one, that is currently logged in.
     * 	It prevents administrators from deleting themselves.
     * 	@return	All users, exept the one, that is currently logged in.
     */
    public List<User> getAllUsersExceptCurrent() {
	Integer currentUserId = FacesHelper.findSessionUser().getId();
	return FinderService.findAllData(User.class).stream() //
		.filter(u -> u.getId() != currentUserId) //
		.collect(Collectors.toList());
    }

    /**	
     * 	@return	Usernames of users, that have the writing permission.	
     */
    public List<String> getAllUsernamesWithWritingPermission() {
	List<String> usernames = new ArrayList<String>();
	for (User user : userService.findUsersWithPermission(Permission.WRITE)) {
	    usernames.add(user.getUsername());
	}
	return usernames;
    }
}

src/main/webapp/authentifiziert/aktivitaeten.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">

		<h2 class="sideHeadline">Aktivitäten</h2>

		<h:form>
			<h:dataTable class="table table-hover" var="action"
				value="#{actionManagedBean.actions}"
				rendered="#{not empty actionManagedBean.actions}"
				columnClasses="iconColumn,executionDateColumn,activatorColumn,detailColumn">

				<h:column>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeObjCreated}">
						<span class="glyphicon glyphicon-plus" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeObjEdited}">
						<span class="glyphicon glyphicon-pencil" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeObjDeleted}">
						<span class="glyphicon glyphicon-trash" />
					</p:outputLabel>

					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventContinued}">
						<span class="glyphicon glyphicon-bookmark" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventRejected}">
						<span class="glyphicon glyphicon-pause" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventRevived}">
						<span class="glyphicon glyphicon-play" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventApproved}">
						<span class="glyphicon glyphicon-ok" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventCancelled}">
						<span class="glyphicon glyphicon-remove" />
					</p:outputLabel>
					<p:outputLabel
						rendered="#{action.actionType eq enumManagedBean.typeEventArchived}">
						<span class="glyphicon glyphicon-book" />
					</p:outputLabel>
				</h:column>

				<h:column>
					<f:facet name="header">Ausgeführt am</f:facet>
					<h:outputText value="#{action.executedOn}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">Ausgeführt von</f:facet>
					#{action.activator}
				</h:column>

				<h:column>
					<f:facet name="header">Detail</f:facet>
	    			 #{action.description}
				</h:column>
			</h:dataTable>

			<h4>
				<h:outputText value="Es sind keine Einträge vorhanden."
					rendered="#{empty actionManagedBean.actions}" />
			</h4>

		</h:form>


	</div>

	<sefb:footer />
	<sefb:js-footer />

</h:body>
</html>

src/main/webapp/authentifiziert/archiv.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">

		<h2 class="sideHeadline">Archiv</h2>

		<h:form id="archivedEventsTable">

			<h:dataTable class="table table-hover" var="event"
				value="#{archivedEventManagedBean.archivedEvents}"
				binding="#{dataTableManagedBean.htmlDataTable}"
				rendered="#{not empty archivedEventManagedBean.archivedEvents}">

				<h:column>
					<f:facet name="header">Veranstaltungsname</f:facet>  
	    			 #{event.eventname}
				</h:column>

				<h:column>
					<f:facet name="header">Beginn</f:facet>
					<h:outputText value="#{event.start}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">Ende</f:facet>
					<h:outputText value="#{event.end}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">Letzter Status</f:facet>
					<h:outputText value="#{event.lastStatus.toString()}" />
				</h:column>

				<h:column
					rendered="#{loginManagedBean.hasUserWritingPermission}">
					<f:facet name="header">Löschen</f:facet>
					<p:commandLink
						actionListener="#{archivedEventManagedBean.deleteEvent}" update="archivedEventsTable">
						<p:confirm header="Bestätigung"
							message="Sind Sie sicher, dass Sie die Veranstaltung #{event.eventname} endgültig löschen möchten?"/>
						<span class="glyphicon glyphicon-trash" />
					</p:commandLink>
				</h:column>

			</h:dataTable>

			<h4>
				<h:outputText value="Es sind keine Einträge vorhanden."
					rendered="#{empty archivedEventManagedBean.archivedEvents}" />
			</h4>
		</h:form>

	</div>
	
	<sefb:footer />
	<sefb:confirmationDialog />	
	<sefb:js-footer />
	
</h:body>
</html>

src/main/webapp/authentifiziert/benutzer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">

		<h2>Benutzerverwaltung</h2>
		<p class="sideHeadline">Hier können Sie alle Nutzer sehen und
			verwalten. Um die eigenen Rechte zu bearbeiten, müssen Sie die Änderungen von einem 
			anderen Account mit Administratorrechten aus vornehmen.</p>


		<h:form id="userSummaryTable">
			<h:dataTable class="table table-hover summaryTable" var="user"
				value="#{userManagedBean.allUsersExceptCurrent}"
				binding="#{dataTableManagedBean.htmlDataTable}"
				rendered="#{not empty userManagedBean.allUsersExceptCurrent}">

				<h:column>
					<f:facet name="header">Benutzername</f:facet>  
    				#{user.username}
				</h:column>

				<h:column>
					<f:facet name="header">Rechte</f:facet>
					<ui:repeat var="permission" value="#{user.permissions}">
							#{permission.toString()}<br />
					</ui:repeat>
				</h:column>

				<h:column>
					<h:commandLink action="#{userManagedBean.editUser}">
						<span class="glyphicon glyphicon-pencil" /> Bearbeiten
					</h:commandLink>
				</h:column>

				<h:column>
					<p:commandLink actionListener="#{userManagedBean.deleteUser}"
						update="userSummaryTable">
						<p:confirm header="Bestätigung"
							message="Sind Sie sicher, dass Sie den Benutzer #{user.username} endgültig löschen möchten?" />
						<span class="glyphicon glyphicon-trash" /> Löschen
					</p:commandLink>
				</h:column>

			</h:dataTable>

			<h4>
				<h:outputText value="Außer Ihnen gibt es keine anderen Benutzer."
					rendered="#{empty userManagedBean.allUsersExceptCurrent}" />
			</h4>

		</h:form>

		<h:link class="btn btn-primary pull-right create-btn"
			outcome="/authentifiziert/benutzer/neu.xhtml">
			<span class="glyphicon glyphicon-plus" /> Neuer Benutzer</h:link>

	</div>

	<sefb:footer />
	<sefb:confirmationDialog />
	<sefb:js-footer />

</h:body>
</html>

src/main/webapp/authentifiziert/pruefschritte.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<f:metadata>
	<f:viewAction action="#{teststepManagedBean.onLoad}" />
</f:metadata>

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">

		<h2>Prüfschrittverwaltung</h2>

		<h:form id="newTeststepForm" class="newChildHeader">
			
			<h:messages id="newTeststepFormMessages" class="errorMessages"
					showDetail="true" showSummary="false"/>
			
			<p:outputLabel for="newTeststepInput" class="newChildHeaderEle">Prüfschrittname: </p:outputLabel>
			<p:inputText id="newTeststepInput" class="newChildHeaderEleInput"
				value="#{teststepManagedBean.newTeststep.teststepname}" required="true"
						requiredMessage="Der Prüfschrittname darf nicht leer sein!"
						a:placeholder="Name des neuen Prüfschritts"/>
			<h:commandLink class="btn btn-primary newChildHeaderBtn"
				action="#{teststepManagedBean.addTeststep}">Prüfschritt anlegen</h:commandLink>
		</h:form>


		<h:form id="allTeststeps">
			<h:dataTable class="table table-hover" var="teststep"
				value="#{teststepManagedBean.testprocessModel.teststeps}"
				binding="#{dataTableManagedBean.htmlDataTable}"
				rendered="#{not empty teststepManagedBean.testprocessModel.teststeps}">

				<h:column>
					<f:facet name="header">Name</f:facet>
					<h:outputText value="#{teststep.teststepname}" />
				</h:column>

				<h:column>
					<h:commandLink action="#{teststepManagedBean.openTeststep}">
						<span class="glyphicon glyphicon-eye-open" /> Öffnen
					</h:commandLink>
				</h:column>

				<h:column>
					<p:commandLink action="#{teststepManagedBean.deleteTeststep}"
						update="allTeststeps">
						<p:confirm header="Bestätigung"
							message="Sind Sie sicher, dass Sie den Prüfschritt #{teststep.teststepname} endgültig löschen möchten?" />
						<span class="glyphicon glyphicon-trash" /> Löschen
					</p:commandLink>
				</h:column>

			</h:dataTable>

			<h4>
				<h:outputText value="Es wurden bisher keine Prüfschritte angelegt."
					rendered="#{empty teststepManagedBean.testprocessModel.teststeps}" />
			</h4>

		</h:form>
	</div>

	<sefb:footer />
	<sefb:confirmationDialog />
	<sefb:js-footer />

</h:body>
</html>

src/main/webapp/authentifiziert/veranstaltungen.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">

		<h2 class="sideHeadline">Veranstaltungen</h2>

		<h:form id="eventTable">
			<p:outputLabel class="filterDropdownLabel" value="Filtern nach:"
				for="eventFilter" />
			<p:selectOneMenu id="eventFilter" class="filterDropdown"
				value="#{eventManagedBean.selectedEventStatus}">
				<f:selectItems value="#{enumManagedBean.allEventStatus}" var="status"
					itemLabel="Status &quot;#{status.toString()}&quot;" />
				<f:ajax render="eventTable" />
			</p:selectOneMenu>
			
			<h:dataTable class="table table-hover" var="event"
				value="#{eventManagedBean.filteredEvents}"
				binding="#{dataTableManagedBean.htmlDataTable}"
				rendered="#{not empty eventManagedBean.filteredEvents}"
				columnClasses="eventnameColumn,usernameColumn,startdateColumn,enddateColumn,editBtnColumn,otherBtnColumn,otherBtnColumn">

				<h:column>
					<f:facet name="header">Veranstaltungsname</f:facet>  
	    			 #{event.eventname}
				</h:column>

				<h:column>
					<f:facet name="header">Bearbeiter</f:facet>
					<h:outputText value="#{event.user.username eq null ? '' : event.user.username}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">Beginn</f:facet>
					<h:outputText value="#{event.start}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column>
					<f:facet name="header">Ende</f:facet>
					<h:outputText value="#{event.end}">
						<f:convertDateTime type="date" pattern="dd.MM.yyyy, HH:mm" />
					</h:outputText>
				</h:column>

				<h:column
					rendered="#{loginManagedBean.hasUserWritingPermission}">
					<h:commandLink action="#{eventManagedBean.editEvent}">
						<span class="glyphicon glyphicon-pencil" /> Bearbeiten
					</h:commandLink>
				</h:column>

				<h:column
					rendered="#{loginManagedBean.hasUserWritingPermission and eventManagedBean.selectedEventStatus eq enumManagedBean.rejected}">
					<h:commandLink action="#{eventManagedBean.reviveEvent}">
						<span class="glyphicon glyphicon-share-alt" /> In Prüfung nehmen
					</h:commandLink>
				</h:column>

				<h:column
					rendered="#{loginManagedBean.hasUserWritingPermission and  eventManagedBean.selectedEventStatus eq enumManagedBean.underExamination}">
					<h:commandLink action="#{eventManagedBean.openInTestProcessWizard}">
						<span class="glyphicon glyphicon-eye-open" /> Öffnen
					</h:commandLink>
				</h:column>

				<h:column
					rendered="#{loginManagedBean.hasUserWritingPermission and  
						(eventManagedBean.selectedEventStatus eq enumManagedBean.approved or eventManagedBean.selectedEventStatus eq enumManagedBean.cancelled)}">
					<p:commandLink action="#{eventManagedBean.archiveEvent}"
						update="eventTable">
						<p:confirm header="Bestätigung"
							message="Sind Sie sicher, dass Sie die Veranstaltung #{event.eventname} archivieren möchten?"/>
						<span class="glyphicon glyphicon-book" /> Archivieren
					</p:commandLink>
				</h:column>
			</h:dataTable>

			<h4>
				<h:outputText value="Es sind keine Einträge vorhanden."
					rendered="#{empty eventManagedBean.filteredEvents}" />
			</h4>

		</h:form>

		<h:link class="btn btn-primary pull-right create-btn"
			outcome="/authentifiziert/veranstaltungen/neu.xhtml"
			rendered="#{loginManagedBean.hasUserWritingPermission}">
			<span class="glyphicon glyphicon-plus" /> Neue Veranstaltung</h:link>
	</div>

	<sefb:footer />
	<sefb:confirmationDialog />
	<sefb:js-footer />
</h:body>
</html>