src/main/java/mb/EditEventManagedBean.java
package mb;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.Optional;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.commons.lang3.time.DateUtils;

import bo.Event;
import helper.FacesHelper;
import provider.OutcomeStatusProvider;
import services.EventService;
import services.FinderService;
import services.ServiceFactory;
import services.UserService;

/**	Managed Bean, that is responsible for editing an existing event object and updates it in the persistence layer.
 * 	@author	Annina Biermann
 */
@ManagedBean
@ViewScoped
public class EditEventManagedBean implements Serializable {
    private static final long serialVersionUID = -6950866155174464530L;

    /**	An event service for event related interactions.	*/
    private transient EventService eventService = ServiceFactory.createEventService();
    /**	An user service for user related interactions.	*/
    private transient UserService userService = ServiceFactory.createUserService();

    /**	The ID of the event, that is edited.	*/
    private Integer eventId;
    /**	The event, that is edited.	*/
    private Event editedEvent;
    /**	The selected username from the dropdown.	*/
    private String usernameOfEditor;

    /**	Finds the event related to the commited ID.
     * 	If no event could be found, the user is returned to the event overview.
     * 	@see		faces-config
     * 	@return	The redirection, depending on a successful ID resolving.
     */
    public String onLoad() {
	Optional<Event> optEvent = FinderService.findById(Event.class, eventId);
	if (optEvent.isPresent()) {
	    editedEvent = optEvent.get();
	    setUsernameOfEditor();
	    return "";
	}
	return OutcomeStatusProvider.FAIL;
    }

    /**	Validates and updates the edited event and passes it to the persistence layer.
     * 	@see		faces-config
     * 	@return	The redirection, depending on a successful validation/updating.
     */
    public String editEvent() {
	Optional<String> validationMessage = eventService.validateEvent(editedEvent);
	if (!validationMessage.isPresent()) {
	    editedEvent.setUser(userService.findUserByUsername(usernameOfEditor).get());
	    eventService.updateEvent(editedEvent);
	    return OutcomeStatusProvider.SUCCESS;
	}
	FacesHelper.createErrorMessage(validationMessage.get(), "editedEventMessages");
	return "";
    }

    /**	Sets the username of the editor string, that's needed for the 
     * 	dropdown menue. 
     * 	The editor of an event can be null, e.g. when it is deleted.
     */
    private void setUsernameOfEditor() {
	if (editedEvent.getUser() != null) {
	    usernameOfEditor = editedEvent.getUser().getUsername();
	}
    }

    // GETTER AND SETTER

    public Date getCurrentDate() {
	return DateUtils.truncate(new Date(), Calendar.DATE);
    }

    public Integer getEventId() {
	return eventId;
    }

    public void setEventId(Integer eventId) {
	this.eventId = eventId;
    }

    public Event getEditedEvent() {
	return editedEvent;
    }

    public void setEditedEvent(Event newEvent) {
	this.editedEvent = newEvent;
    }

    public String getUsernameOfEditor() {
	return usernameOfEditor;
    }

    public void setUsernameOfEditor(String usernameOfEditor) {
	this.usernameOfEditor = usernameOfEditor;
    }
}

src/main/java/mb/EnumManagedBean.java
package mb;

import java.util.Arrays;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import enums.ActionType;
import enums.EditingSuggestion;
import enums.EventStatus;
import enums.Permission;

/**	Managed Bean to make specific enum objects accessable to the EL.
 * 	@author 	Annina Biermann
 */
@ManagedBean
@RequestScoped
public class EnumManagedBean {

    // ACTION TYPES

    public ActionType getTypeObjCreated() {
	return ActionType.OBJECT_CREATED;
    }

    public ActionType getTypeObjEdited() {
	return ActionType.OBJECT_EDITED;
    }

    public ActionType getTypeObjDeleted() {
	return ActionType.OBJECT_DELETED;
    }

    public ActionType getTypeEventRejected() {
	return ActionType.EVENT_REJECTED;
    }

    public ActionType getTypeEventRevived() {
	return ActionType.EVENT_REVIVED;
    }

    public ActionType getTypeEventApproved() {
	return ActionType.EVENT_APPROVED;
    }

    public ActionType getTypeEventCancelled() {
	return ActionType.EVENT_CANCELLED;
    }

    public ActionType getTypeEventArchived() {
	return ActionType.EVENT_ARCHIVED;
    }

    public ActionType getTypeEventContinued() {
	return ActionType.EVENT_CONTINUED;
    }

    // EDITING SUGGESTIONS

    public EditingSuggestion getNoEditingSuggestion() {
	return EditingSuggestion.NO_EDITING;
    }

    public EditingSuggestion getGeneralEditingSuggestion() {
	return EditingSuggestion.GENERAL_EDITING;
    }

    public EditingSuggestion getContinuingEditingSuggestion() {
	return EditingSuggestion.CONTINUING_EDITING;
    }

    // EVENT STATUS

    public EventStatus getUnderExamination() {
	return EventStatus.UNDER_EXAMINATION;
    }

    public EventStatus getRejected() {
	return EventStatus.REJECTED;
    }

    public EventStatus getApproved() {
	return EventStatus.APPROVED;
    }

    public EventStatus getCancelled() {
	return EventStatus.CANCELLED;
    }

    public List<EventStatus> getAllEventStatus() {
	return Arrays.asList(EventStatus.values());
    }

    // PERMISSIONS

    public List<Permission> getAllPermissions() {
	return Arrays.asList(Permission.values());
    }
}

src/main/java/mb/TestprocessManagedBean.java
package mb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import bo.Event;
import bo.Teststep;
import bo.Testsubcriterion;
import enums.EditingSuggestion;
import helper.TestprocessHelper;
import provider.OutcomeStatusProvider;
import services.ActionService;
import services.EventService;
import services.FinderService;
import services.ServiceFactory;
import services.TestprocessService;
import services.TeststepService;

/**	A Managed Bean responsible for testprocess related user interactions.
 * 	@author	Annina Biermann
 */
@ManagedBean
@ViewScoped
public class TestprocessManagedBean implements Serializable {
    private static final long serialVersionUID = -784562966927922117L;

    /**	An action service for logging and finding actions.	*/
    private transient ActionService actionService = ServiceFactory.createActionService();
    /**	An testprocess service for testprocess related interactions.	*/
    private transient TestprocessService testprocessService = ServiceFactory.createTestprocessService();
    /**	An testprocess service for teststep related interactions.	*/
    private transient TeststepService teststepService = ServiceFactory.createTeststepService();
    /**	An event service for event related interactions.	*/
    private transient EventService eventService = ServiceFactory.createEventService();

    /**	The ID of the event currently shown in the view.	*/
    private Integer eventId;
    /**	The event currently shown in the view.	*/
    private Event event;

    /**	The current calculated editing suggestion.	*/
    private EditingSuggestion currentEditingSuggestion;
    /**	The current teststep of the event.	*/
    private Teststep currentTeststep;

    /**	Initialized the attributes of the Managed Bean.
     * 	If no event could be found or another error occurs, the user is returned to the event overview.
     * 	@see		faces-config
     * 	@return	The redirection, depending on a successful ID resolving.
     */
    public String onLoad() {
	Optional<Event> optEvent = FinderService.findById(Event.class, eventId);
	if (optEvent.isPresent()) {
	    setEvent(optEvent.get());
	    setCurrentTeststep(testprocessService.findCurrentTeststep(getEvent().getTestprocess()));
	    updateSuggestion();
	    return "";
	}
	return OutcomeStatusProvider.FAIL;
    }

    /**	Saves a subcriterion that is marked checked/unchecked on the event.
     * 	@param 	testsubcriterion	the subcriterion, that is selected	
     */
    public void saveFulfilled(Testsubcriterion testsubcriterion) {
	updateSuggestion();
	if (testsubcriterion.isFulfilled()) {
	    actionService.logTestsubcriterionMarkedFulfilled(event, testsubcriterion);
	} else {
	    actionService.logTestsubcriterionMarkedNotFulfilled(event, testsubcriterion);
	}
	teststepService.updateTestsubcriterion(testsubcriterion);
    }

    /**	Saves a subcriterion that is marked relevant/irrelecant on the event.
     * 	@param 	testsubcriterion	the subcriterion, that is selected	
     */
    public void saveIrrelevant(Testsubcriterion testsubcriterion) {
	updateSuggestion();
	if (testsubcriterion.isIrrelevant()) {
	    actionService.logTestsubcriterionMarkedIrrelevant(event, testsubcriterion);
	} else {
	    actionService.logTestsubcriterionMarkedRelevant(event, testsubcriterion);
	}
	teststepService.updateTestsubcriterion(testsubcriterion);
    }

    /**	Takes the event to the next teststep.
     * 	@return	The URL of the next teststep in the testprocess wizard.
     */
    public String nextStep() {
	teststepService.fulfillTeststep(currentTeststep);
	actionService.logEventContinued(event, currentTeststep);
	return "pruefprozessassistent?faces-redirect=true&eventId=" + eventId;
    }

    /**	Sets the status of the event to rejected.
     * 	@see		faces-config
     * 	@return	The reference to the event overview.
     */
    public String rejectEvent() {
	eventService.rejectEvent(event);
	actionService.logEventRejected(event);
	return OutcomeStatusProvider.SUCCESS;
    }

    /**	Sets the status of the event to approved.
     * 	@see		faces-config
     * 	@return	The reference to the event overview.
     */
    public String approveEvent() {
	eventService.approveEvent(event);
	actionService.logEventApproved(event);
	return OutcomeStatusProvider.SUCCESS;
    }

    /**	Sets the status of the event to cancelled.
     * 	@see		faces-config
     * 	@return	The reference to the event overview.
     */
    public String cancelEvent() {
	eventService.cancelEvent(event);
	actionService.logEventCancelled(event);
	return OutcomeStatusProvider.SUCCESS;
    }

    /**	Calculates the rate of the current event and returns the fullfilled / count of all subcriteria rate as a string.
     * 	@return	The fullfilled / count of all subcriteria rate as a string.
     */
    public String calculateRate() {
	return String.valueOf(TestprocessHelper.calculateRate(currentTeststep));
    }

    /**	Depending on the calculated rate, a editing suggestion is evaluated.
     * 	@return	The evaluated suggestion.
     */
    public String getEditingSuggestionLabel() {
	return getCurrentEditingSuggestion().getSuggestionLabel();
    }

    /**	Depending on the editing suggestion, a style class for the editing suggestion is returned.
     * 	@see		The testprocess.css file in the resources.
     * 	@return	A style class for the editing suggestion is returned.
     */
    public String getEditingSuggestionStyleClass() {
	return getCurrentEditingSuggestion().getStyleClass();
    }

    /**	
     * 	@return	A boolean, if the current event is in the last teststep.
     */
    public boolean isLastStep() {
	List<Teststep> teststeps = new ArrayList<>();
	teststeps.addAll(event.getTestprocess().getTeststeps());
	return teststeps.indexOf(currentTeststep) == (teststeps.size() - 1);
    }

    /**	Updates the editing suggestion.
     */
    private void updateSuggestion() {
	currentEditingSuggestion = TestprocessHelper.resolveEditingSuggestion(currentTeststep);
    }

    // GETTER AND SETTER

    public Integer getEventId() {
	return eventId;
    }

    public void setEventId(Integer eventId) {
	this.eventId = eventId;
    }

    public Event getEvent() {
	return event;
    }

    public void setEvent(Event event) {
	this.event = event;
    }

    public Teststep getCurrentTeststep() {
	return currentTeststep;
    }

    public void setCurrentTeststep(Teststep currentTeststep) {
	this.currentTeststep = currentTeststep;
    }

    public EditingSuggestion getCurrentEditingSuggestion() {
	return currentEditingSuggestion;
    }
}

src/main/java/mb/UserManagedBean.java
package mb;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import bo.User;
import enums.Permission;
import helper.FacesHelper;
import services.ActionService;
import services.FinderService;
import services.ServiceFactory;
import services.UserService;

/**	A Managed Bean responsible for user related user interactions.
 * 	@author	Annina Biermann
 */
@ManagedBean
@RequestScoped
public class UserManagedBean {

    /**	An action service for logging and finding actions.	*/
    private transient ActionService actionService = ServiceFactory.createActionService();
    /**	An user service for user related interactions.	*/
    private transient UserService userService = ServiceFactory.createUserService();

    /**	Redirects to the user editing view and passes the user ID to the view.
     * 	@return	The redirect URL.
     */
    public String editUser() {
	User selectedUser = FacesHelper.getSelectedObject(User.class);
	return "benutzer/bearbeiten?faces-redirect=true&userId=" + selectedUser.getId();
    }

    /**	Deletes the selected user off the persistence layer.
     * 	@return	The reference to the same page.
     */
    public String deleteUser() {
	User selectedUser = FacesHelper.getSelectedObject(User.class);
	ServiceFactory.createUserService().deleteUser(selectedUser);
	actionService.logUserDeletion(selectedUser);
	return "";
    }

    /**	Returns all users, except the one, that is currently logged in.
     * 	It prevents administrators from deleting themselves.
     * 	@return	All users, exept the one, that is currently logged in.
     */
    public List<User> getAllUsersExceptCurrent() {
	Integer currentUserId = FacesHelper.findSessionUser().getId();
	return FinderService.findAllData(User.class).stream() //
		.filter(u -> u.getId() != currentUserId) //
		.collect(Collectors.toList());
    }

    /**	
     * 	@return	Usernames of users, that have the writing permission.	
     */
    public List<String> getAllUsernamesWithWritingPermission() {
	List<String> usernames = new ArrayList<String>();
	for (User user : userService.findUsersWithPermission(Permission.WRITE)) {
	    usernames.add(user.getUsername());
	}
	return usernames;
    }
}

src/main/webapp/authentifiziert/veranstaltungen/bearbeiten.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<f:metadata>
	<f:viewParam name="eventId" value="#{editEventManagedBean.eventId}" />
	<f:viewAction action="#{editEventManagedBean.onLoad}" />
</f:metadata>

<h:body>

	<sefb:navbar />

		<div class="underNavContainer">
			<h:link class="backButton" outcome="/authentifiziert/veranstaltungen.xhtml">
				<span class="glyphicon glyphicon-arrow-left" /> Zurück zu Veranstaltungen
			</h:link>

	<div class="formContainer">
			<div class="eventCreateFormContainer">
				<h3>Veranstaltung #{editEventManagedBean.editedEvent.eventname} bearbeiten</h3>
				<h:form id="createEventForm">

					<h:messages id="editedEventMessages" class="errorMessages"
						showDetail="true" showSummary="false" />

					<div class="form-group">
						<p:outputLabel for="eventname" value="Veranstaltungsname:" />
						<p:inputText id="eventname" class="inputText" required="true"
							requiredMessage="Der Veranstaltungsname darf nicht leer sein!"
							value="#{editEventManagedBean.editedEvent.eventname}" />
					</div>

					<div class="form-group">
						<p:outputLabel for="start" value="Beginn:" />
						<br />
						<p:calendar id="start" class="inputText"
							value="#{editEventManagedBean.editedEvent.start}" locale="de"
							pattern="dd.MM.yyyy HH:mm" required="true"
							requiredMessage="Der Starttermin darf nicht leer sein!"
							readOnlyInputText="#{true}" />
					</div>

					<div class="form-group">
						<p:outputLabel for="finish" value="Ende:" />
						<br />
						<p:calendar id="finish" class="inputText"
							value="#{editEventManagedBean.editedEvent.end}" locale="de" required="true"
							requiredMessage="Der Endtermin darf nicht leer sein!"
							pattern="dd.MM.yyyy HH:mm" readOnlyInputText="#{true}" />
					</div>

					<div class="form-group">
						<p:outputLabel for="editor" value="Bearbeiter:" />
						<br />
						<p:selectOneMenu id="editor" required="true"
							requiredMessage="Der Bearbeiter darf nicht leer sein!"
							value="#{editEventManagedBean.usernameOfEditor}" class="inputText" >
							<f:selectItem itemValue="#{null}" itemLabel="Wählen Sie einen Benutzer..." itemDisabled="#{editEventManagedBean.usernameOfEditor != null}"/>
							<f:selectItems
								value="#{userManagedBean.allUsernamesWithWritingPermission}" />
						</p:selectOneMenu>
					</div>

					<h:commandLink class="btn btn-primary pull-right create-btn"
						action="#{editEventManagedBean.editEvent}">Speichern</h:commandLink>
				</h:form>
			</div>
		</div>
	</div>

	<sefb:footer />
	<sefb:js-footer />
	
</h:body>
</html>

src/main/webapp/authentifiziert/veranstaltungen/neu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">
		<h:link class="backButton"
			outcome="/authentifiziert/veranstaltungen.xhtml">
			<span class="glyphicon glyphicon-arrow-left" /> Zurück zu den Veranstaltungen
		</h:link>

		<div class="formContainer">
			<div class="eventCreateFormContainer">
				<h3>Neue Veranstaltung anlegen</h3>
				<h:form id="createEventManagedBeanForm">

					<h:messages id="newEventMessages" class="errorMessages"
						showDetail="true" showSummary="false" />

					<div class="form-group">
						<p:outputLabel for="eventname" value="Veranstaltungsname:" />
						<p:inputText id="eventname" class="inputText" required="true"
							requiredMessage="Der Veranstaltungsname darf nicht leer sein!"
							value="#{createEventManagedBean.newEvent.eventname}" 
							a:placeholder="Name der neuen Veranstaltung"/>
					</div>

					<div class="form-group">
						<p:outputLabel for="start" value="Beginn:"/>
						<br />
						<p:calendar id="start" class="inputText"
							value="#{createEventManagedBean.newEvent.start}" locale="de"
							pattern="dd.MM.yyyy HH:mm" 
							mindate="#{createEventManagedBean.currentDate}" required="true"
							requiredMessage="Der Starttermin darf nicht leer sein!"
							readOnlyInputText="#{true}">
								<p:ajax update="end"/>
							</p:calendar>
					</div>

					<div class="form-group">
						<p:outputLabel for="end" value="Ende:" />
						<br />
						<p:calendar id="end" class="inputText"
							value="#{createEventManagedBean.newEvent.end}" locale="de"
							pattern="dd.MM.yyyy HH:mm"
							mindate="#{createEventManagedBean.newEvent.start}" required="true"
							requiredMessage="Der Endtermin darf nicht leer sein!"
							readOnlyInputText="#{true}" />
					</div>

					<div class="form-group">
						<p:outputLabel for="editor" value="Bearbeiter:" />
						<br />
						<p:selectOneMenu id="editor" required="true"
							requiredMessage="Der Bearbeiter darf nicht leer sein!"
							value="#{createEventManagedBean.usernameOfEditor}" class="inputText">
							<f:selectItem itemValue="#{null}" itemLabel="Wählen Sie einen Benutzer..."/>
							<f:selectItems
								value="#{userManagedBean.allUsernamesWithWritingPermission}" />
						</p:selectOneMenu>
					</div>

					<h:commandLink class="btn btn-primary pull-right create-btn"
						action="#{createEventManagedBean.createEvent}">Veranstaltung anlegen</h:commandLink>
				</h:form>
			</div>
		</div>
	</div>

	<sefb:footer />
	<sefb:js-footer />

</h:body>
</html>

src/main/webapp/authentifiziert/veranstaltungen/pruefprozessassistent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sefb="http://sefb.com/facelets">

<sefb:head />

<f:metadata>
	<f:viewParam name="eventId" value="#{testprocessManagedBean.eventId}" />
	<f:viewAction action="#{testprocessManagedBean.onLoad}" />
</f:metadata>

<h:body>

	<sefb:navbar />

	<div class="underNavContainer">
		<h:link class="backButton"
			outcome="/authentifiziert/veranstaltungen.xhtml">
			<span class="glyphicon glyphicon-arrow-left" /> Zurück zu Veranstaltungen
		</h:link>

		<h:form id="wizardFormId">
			<h2 class="sideHeadline">#{testprocessManagedBean.event.eventname}:
				#{testprocessManagedBean.currentTeststep.teststepname}</h2>

			<p:panelGrid class="completionTestStepTable">
				<f:facet name="header">
					<p:row>
						<p:column colspan="6">
							<h:outputText value="Kriterien" />
						</p:column>
						<p:column colspan="2">
							<h:outputText value="Punktwert" />
						</p:column>
						<p:column colspan="2">
							<h:outputText value="erfüllt?" />
						</p:column>
						<p:column colspan="2"
							rendered="#{testprocessManagedBean.currentTeststep.irrelevantAllowed}">
							<h:outputText value="irrelevant?" />
						</p:column>
					</p:row>
				</f:facet>


				<ui:repeat var="testcriterion"
					value="#{testprocessManagedBean.currentTeststep.testcriteria}">

					<p:row>
						<p:column colspan="12">
							<h4>
								<h:outputText value="#{testcriterion.testcriterionname}" />
							</h4>
						</p:column>
						<ui:repeat var="testsubcriterion"
							value="#{testcriterion.testsubcriteria}">
							<p:row>
								<p:column colspan="6">
									<h:outputText class="testsubcriterionname"
										value="#{testsubcriterion.testsubcriterionname}" />
								</p:column>
								<p:column colspan="2">
									<h:outputText value="#{testsubcriterion.score}" />
								</p:column>
								<p:column colspan="2">
									<p:selectBooleanCheckbox value="#{testsubcriterion.fulfilled}"
										disabled="#{testsubcriterion.irrelevant}">
										<p:ajax update="@form"
											listener="#{testprocessManagedBean.saveFulfilled(testsubcriterion)}" />
									</p:selectBooleanCheckbox>
								</p:column>
								<p:column colspan="2"
									rendered="#{testprocessManagedBean.currentTeststep.irrelevantAllowed}">
									<p:selectBooleanCheckbox value="#{testsubcriterion.irrelevant}">
										<p:ajax update="@form"
											listener="#{testprocessManagedBean.saveIrrelevant(testsubcriterion)}" />
									</p:selectBooleanCheckbox>
								</p:column>
							</p:row>
						</ui:repeat>
					</p:row>
				</ui:repeat>
			</p:panelGrid>


			<div class="suggestion">
				<p:panelGrid class="suggestionGrid" columns="2" layout="grid">
					<h:outputLabel value="Erfüllt:" for="completionTeststepRate" />
					<h:outputText id="completionTeststepRate"
						value="#{testprocessManagedBean.calculateRate()} %" />
					<h:outputLabel value="Empfehlung:"
						for="completionTestStepSuggestion" />
					<h:outputText id="completionTestStepSuggestion"
						class="testStepSuggestion"
						value="#{testprocessManagedBean.editingSuggestionLabel}"
						styleClass="#{testprocessManagedBean.editingSuggestionStyleClass}" />
				</p:panelGrid>
			</div>

			<div class="wizardButtons">
				<p:commandButton class="btn btn-danger btn-lg"
					value="Veranstaltung ablehnen"
					action="#{testprocessManagedBean.cancelEvent}"
					disabled="#{testprocessManagedBean.currentEditingSuggestion != enumManagedBean.noEditingSuggestion}">
					<p:confirm header="Bestätigung"
						message="Sind Sie sicher, dass Sie die Veranstaltung endgültig ablehnen möchten?" />
				</p:commandButton>

				<p:commandButton class="btn btn-warning btn-lg"
					value="Veranstaltung zurückweisen"
					action="#{testprocessManagedBean.rejectEvent}"
					disabled="#{testprocessManagedBean.currentEditingSuggestion != enumManagedBean.generalEditingSuggestion}">
					<p:confirm header="Bestätigung"
						message="Sind Sie sicher, dass Sie die Veranstaltung zur Nachbesserung zurückweisen möchten?" />
				</p:commandButton>

				<p:commandButton class="btn btn-primary btn-lg"
					value="Nächster Prüfschritt"
					action="#{testprocessManagedBean.nextStep}"
					disabled="#{testprocessManagedBean.currentEditingSuggestion != enumManagedBean.continuingEditingSuggestion}"
					rendered="#{!testprocessManagedBean.lastStep}">
					<p:confirm header="Bestätigung"
						message="Sind Sie sicher, dass Sie die Veranstaltung in den nächsten Prüfschritt bringen möchten?" />
				</p:commandButton>

				<p:commandButton class="btn btn-success btn-lg"
					value="Veranstaltung genehmigen"
					action="#{testprocessManagedBean.approveEvent()}"
					update="wizardFormId"
					disabled="#{testprocessManagedBean.currentEditingSuggestion != enumManagedBean.continuingEditingSuggestion}"
					rendered="#{testprocessManagedBean.lastStep}">
					<p:confirm header="Bestätigung"
						message="Sind Sie sicher, dass Sie die Veranstaltung gehemigen möchten?" />
				</p:commandButton>
			</div>

		</h:form>
	</div>

	<sefb:footer />
	<sefb:confirmationDialog />
	<sefb:js-footer />

</h:body>
</html>