src/main/java/mb/LoginManagedBean.java
package mb;

import java.io.Serializable;
import java.util.Optional;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import enums.Permission;
import helper.FacesHelper;
import provider.OutcomeStatusProvider;
import services.ServiceFactory;
import services.UserService;

/**	Managed Bean, that is responsible for regulating the login and logout of a user.
 * 	It is session scoped, since the current user is needed as long as the session exists.
 * 	@author	Annina Biermann
 */
@ManagedBean(eager = true)
@SessionScoped
public class LoginManagedBean implements Serializable {
    private static final long serialVersionUID = -1381101568311500915L;

    /**	The ID of the user, that is currently logged in.	*/
    private Integer currentUserId;
    /**	A boolean flag, if a user is logged in in the current session.	*/
    private boolean loggedIn = false;

    /**	Credentials for attempts to login.	*/
    private String username;
    private String password;

    /**	Processes an attempt to login. If 
     * 		- the given user is not existing
     * 		- the given password is invalid
     * 	an error message is created and the user remains on the login-page.
     * 	Else the user is successfully authenticated.
     * 	@return	The outcome of the login validation.
     */
    public String login() {
	UserService userService = ServiceFactory.createUserService();
	Optional<String> validateMessage = userService.validateCredentials(username, password);
	if (!validateMessage.isPresent()) {
	    setCurrentUserId(userService.findUserByUsername(username).get().getId());
	    loggedIn = true;
	    return OutcomeStatusProvider.SUCCESS;
	}
	FacesHelper.createErrorMessage(validateMessage.get(), "loginFormMessages");
	return "";
    }

    /**	Deletes the current user from the session and redirects to the login-page.
     * 	@return	The outcome of the logout.
     */
    public String logout() {
	setCurrentUserId(null);
	loggedIn = false;
	FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	return OutcomeStatusProvider.SUCCESS;
    }

    public boolean getHasUserWritingPermission() {
	return ServiceFactory.createUserService().hasUserPermission(currentUserId, Permission.WRITE);
    }

    public boolean getHasUserAdminPermission() {
	return ServiceFactory.createUserService().hasUserPermission(currentUserId, Permission.ADMINISTRATE);
    }

    // GETTER AND SETTER

    public String getUsername() {
	return username;
    }

    public void setUsername(String username) {
	this.username = username;
    }

    public String getPassword() {
	return password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    public Integer getCurrentUserId() {
	return currentUserId;
    }

    public void setCurrentUserId(Integer currentUserId) {
	this.currentUserId = currentUserId;
    }

    public boolean isLoggedIn() {
	return loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
	this.loggedIn = loggedIn;
    }
}

src/main/webapp/WEB-INF/tags/confirmationDialog.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<!-- confirmation dialog for deleting objects, etc. -->
	
	<p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
		<h:form>
			<p:commandButton value="Ja" type="button"
				styleClass="ui-confirmdialog-yes"/>
			<p:commandButton value="Nein" type="button" 
				styleClass="ui-confirmdialog-no"/>
		</h:form>
	</p:confirmDialog>
	
</html>

src/main/webapp/WEB-INF/tags/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

	<div class="footerContainer">
		<h:graphicImage library="images" name="bfwLogo.png" class="coorpLogo" />
		<h:graphicImage library="images" name="htwLogo.png" class="coorpLogo" />
		<br/>
		<br/><h:outputText class="footerText" value="Secure Events For Berlin Version 2.0 - In Kooperation der Berliner Feuerwehr und der Hochschule für Wirtschaft und Technik."></h:outputText>
	</div>
</html>

src/main/webapp/WEB-INF/tags/head.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">
	<h:head>
		<!-- Metainformation -->
		<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
	
		<!-- Title -->
		<title>Secure Events for Berlin</title>
		
		<!-- Favicon -->
		<link rel="shortcut icon" type="image/x-icon" href="#{resource['images/favicon.ico']}"/>
		
		<!-- Stylesheets -->
		<h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap.min-jsf.css" />
	    <h:outputStylesheet library="webjars" name="bootstrap/3.3.6/css/bootstrap-theme.min-jsf.css" />
	    <h:outputStylesheet library="webjars" name="font-awesome/4.5.0/css/font-awesome.min-jsf.css" />
	    
	    <h:outputStylesheet library="css" name="main.css" />
	    <h:outputStylesheet library="css" name="forms.css" />
	    <h:outputStylesheet library="css" name="overview.css" />
	    <h:outputStylesheet library="css" name="loginLogout.css" />
	    <h:outputStylesheet library="css" name="testprocess.css" />
	</h:head>
</html>

src/main/webapp/WEB-INF/tags/js-footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

<!-- Bootstrap & Jquery JS-->
<h:outputScript library="primefaces" name="jquery/jquery.js"
	target="head" />
<h:outputScript library="webjars"
	name="bootstrap/3.3.6/js/bootstrap.min.js" />
<h:outputScript library="js" name="primefacesLocale.js" />
</html>

src/main/webapp/WEB-INF/tags/navbar.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

<h:form rendered="#{loginManagedBean.loggedIn}" class="navForm">
	<div class="navbar navbar-default navbar-fixed-top navbarSefb">
		<div class="nav-container">
			<div class="navbar-header sefbLogoHeader">
				<h:link class="navbar-brand sefbLogoBrand"
					outcome="/authentifiziert/veranstaltungen.xhtml">
					<h:graphicImage library="images" name="sefbLogoBrand.png" class="sefbLogo"/>	
				</h:link>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<li><h:link outcome="/authentifiziert/veranstaltungen.xhtml">
						<span class="glyphicon glyphicon-home nav-glyph" />  Veranstaltungen</h:link></li>
				<li><h:link outcome="/authentifiziert/archiv.xhtml">
						<span class="glyphicon glyphicon-home glyphicon-book" />  Archiv</h:link></li>
				<h:panelGroup rendered="#{loginManagedBean.hasUserAdminPermission}">
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown" role="button"><span
							class="glyphicon glyphicon-cog nav-glyph" /> Einstellungen <span
							class="caret" /></a>
						<ul class="dropdown-menu">
							<li><h:link outcome="/authentifiziert/benutzer.xhtml"> 
									<span class="glyphicon glyphicon-user nav-glyph" />  Benutzerverwaltung</h:link></li>
							<li><h:link outcome="/authentifiziert/pruefschritte.xhtml">
									<span class="glyphicon glyphicon-th-list nav-glyph" />  Prüfschrittverwaltung</h:link></li>
							<li><h:link outcome="/authentifiziert/aktivitaeten.xhtml">
									<span class="glyphicon glyphicon-edit nav-glyph" />  Aktivitätsübersicht</h:link></li>
						</ul></li>
				</h:panelGroup>
				<li><h:commandLink action="#{loginManagedBean.logout}" >
						<span class="glyphicon glyphicon-log-out" /> Abmelden</h:commandLink></li>
			</ul>
		</div>
	</div>
</h:form>
</html>